# Generated by Django 5.2.5 on 2025-10-18 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medical_report_table',
            name='ACCIDENT',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.accident_report_table'),
        ),
    ]
