# Generated by Django 5.2.5 on 2025-10-18 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_medical_report_table_accident'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambulance_table',
            name='rc',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='user_table',
            name='photo',
            field=models.FileField(upload_to=''),
        ),
    ]
