# Generated by Django 5.2.5 on 2025-12-13 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_ambulance_table_rc_alter_user_table_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_table',
            name='post',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.CreateModel(
            name='notification_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('date', models.DateField()),
                ('photo', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=100)),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user_table')),
            ],
        ),
    ]
