# Generated by Django 5.2.5 on 2025-12-16 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_user_table_post_notification_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_table',
            name='post',
        ),
        migrations.AddField(
            model_name='user_table',
            name='pincode',
            field=models.IntegerField(default=1234),
            preserve_default=False,
        ),
    ]
