# Generated by Django 5.2.6 on 2026-01-24 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_user_table_post_user_table_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accident_report_table',
            name='AMBULANCE',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to='myapp.ambulance_table'),
        ),
        migrations.AlterField(
            model_name='accident_report_table',
            name='HOSPITAL',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to='myapp.hospital_table'),
        ),
        migrations.AlterField(
            model_name='accident_report_table',
            name='USER',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to='myapp.user_table'),
        ),
    ]
