# Generated by Django 5.2.6 on 2026-01-28 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_accident_report_table_ambulance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambulance_table',
            name='registration_no',
            field=models.CharField(max_length=50),
        ),
    ]
