# Generated by Django 5.2.6 on 2026-01-31 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_ambulance_table_registration_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accident_report_table',
            name='AMBULANCE',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.ambulance_table'),
        ),
        migrations.AlterField(
            model_name='accident_report_table',
            name='HOSPITAL',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.hospital_table'),
        ),
        migrations.AlterField(
            model_name='accident_report_table',
            name='USER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user_table'),
        ),
        migrations.AlterField(
            model_name='accident_report_table',
            name='photo',
            field=models.FileField(upload_to='accidents/'),
        ),
        migrations.AlterField(
            model_name='notification_table',
            name='photo',
            field=models.FileField(upload_to=''),
        ),
    ]
