# Generated by Django 5.2.6 on 2026-01-31 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_accident_report_table_ambulance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accident_report_table',
            name='view_status',
            field=models.BooleanField(default=False),
        ),
    ]
