# Generated by Django 5.2.6 on 2026-02-01 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_accident_report_table_view_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambulance_table',
            name='act_status',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
